### ISSUE TITLE
Nginx plugin appears broken on Centos 7

### ISSUE THREAD

**Issue by clayreimann** [amonapp/amon-plugins#3]
After `amonpm install nginx` on CentOS 7:

```
Traceback (most recent call last):
  File "/usr/bin/amon-agent.py", line 16, in <module>
    from amonagent.runner import runner
  File "/usr/lib/python2.7/site-packages/amonagent/runner.py", line 12, in <module>
    from amonagent.modules.containers import container_data_collector
  File "/usr/lib/python2.7/site-packages/amonagent/modules/containers.py", line 2, in <module>
    from docker import Client
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 37, in <module>
    import websocket
  File "/usr/lib/python2.7/site-packages/websocket/__init__.py", line 22, in <module>
    from ._core import *
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 41, in <module>
    from ._url import *
  File "/usr/lib/python2.7/site-packages/websocket/_url.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse
```

Still occurs after `yum update`

**Comment by martinrusev** [comment]
Hi @clayreimann, Looking into it, should be fixed in a couple of hours

**Comment by martinrusev** [comment]
Hi @clayreimann, It should be working fine on CentOS 7, I've pushed 2.2.6 and completely removed Docker from the agent (for now, it will be released as a plugin)
